name: Build Android APK (no wrapper)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Java (Android butuh JDK 17)
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Step 3: Setup Gradle (pakai Gradle global)
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Step 4: Build APK
      - name: Build Debug APK
        run: gradle assembleDebug

      # Step 5: Upload hasil build
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: app/build/outputs/apk/debug/app-debug.apk
